name: time_sheet
description: Time picker sheet library, allows you to have beauty time picker sheet with customable design to align with your requirements.
homepage: https://github.com/yoktavian/time-picker-sheet
version: 0.0.2+2

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true